language: php

dist: trusty
sudo: required

php:
  - 7.0

install:
  # updates composer on travis
  - travis_retry composer self-update
  # clear composer cache, might speed up finding new tags
  - travis_retry composer clear-cache
 

script: vendor/bin/phpunit
