language: php

dist: trusty
sudo: true

php:
  - 7.0

before_script:
 - cp .env.travis .env
 - bash .travis-install-mysql-5.7.sh
 - mysql --version
 - mysql -e 'create database c9;'
 - composer self-update
 - composer install --dev --prefer-source --no-interaction
 - php artisan migrate:install --env=testing --no-interaction -vvv

script:
 - php artisan migrate --env=testing --no-interaction -vvv
 - php artisan db:seed --env=testing --no-interaction -vvv
 - vendor/bin/phpunit

services:
  - redis-server
  - mysql
