language: php

dist: trusty
sudo: required

php:
  - 7.0

before_script:
 - bash .travis.install-mysql-5.7.sh
 - cp .env.travis .env
 - composer self-update
 - composer install --dev --prefer-source --no-interaction
 - php artisan migrate:install --env=testing --no-interaction -vvv

script:
 - php artisan migrate --env=testing --no-interaction -vvv
 - php artisan db:seed --env=testing --no-interaction -vvv
 - vendor/bin/phpunit

services:
  - redis-server
  - mysql
